Merge pull request #523 from dasbh/master
Fixed java.lang.NoClassDefFoundError: org/jbehave/core/model/Lifecycle due to old version of jBehave on classpath